version: '3'
services:
  autoheal:
    image: willfarrell/autoheal:v0.7.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
  pencil-ml-backend:
    image: scrat98/pencil-ml-backend:latest
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/ping || exit 1
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
  pencil-ml-frontend:
    image: scrat98/pencil-ml-frontend:latest
    restart: always
    environment:
      - PENCIL_ML_BACKEND_HOST=/pencil-ml-backend
  gw:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - 3000:2020